option(WAYRANDR_COVERAGE "GCC C++ coverage" OFF)
option(WAYRANDR_SANITIZERS "Clang address and undefined behavior sanitizers" OFF)
option(WAYRANDR_FUZZING "Clang libFuzzer instrumentation" OFF)
set(instrumentation_modes 0)
foreach(mode WAYRANDR_COVERAGE WAYRANDR_SANITIZERS WAYRANDR_FUZZING)
    if(${mode})
        math(EXPR instrumentation_modes "${instrumentation_modes} + 1")
    endif()
endforeach()
if(instrumentation_modes GREATER 1)
    message(FATAL_ERROR "Coverage, sanitizers and fuzzing require separate configurations")
endif()
if(WAYRANDR_COVERAGE AND NOT CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    message(FATAL_ERROR "Coverage requires GCC")
endif()
if((WAYRANDR_SANITIZERS OR WAYRANDR_FUZZING) AND NOT CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    message(FATAL_ERROR "Sanitizers and fuzzing require Clang")
endif()
function(wayrandr_instrument target)
    if(WAYRANDR_COVERAGE)
        target_compile_options(${target} PRIVATE --coverage -O0 -g)
        target_link_options(${target} PUBLIC --coverage)
    elseif(WAYRANDR_SANITIZERS)
        target_compile_options(${target} PRIVATE -fsanitize=address,undefined -fno-omit-frame-pointer -g)
        target_link_options(${target} PUBLIC -fsanitize=address,undefined)
    elseif(WAYRANDR_FUZZING)
        target_compile_options(${target} PRIVATE -fsanitize=fuzzer-no-link,address,undefined -fno-omit-frame-pointer -g)
        target_link_options(${target} PUBLIC -fsanitize=fuzzer-no-link,address,undefined)
    endif()
endfunction()
